# Generated by Django 5.1.5 on 2025-02-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0011_alter_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('Rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('Source_Table', models.CharField(blank=True, max_length=255, null=True)),
                ('Source_Field_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Data_Mapping_Rules', models.CharField(blank=True, max_length=255, null=True)),
                ('Target_SAP_Table', models.CharField(blank=True, max_length=255, null=True)),
                ('Target_SAP_Field', models.CharField(blank=True, max_length=255, null=True)),
                ('Text_Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Lookup_Table', models.CharField(blank=True, max_length=255, null=True)),
                ('Look_Up_Required', models.BooleanField(default=False)),
                ('Last_Updated_By', models.CharField(blank=True, max_length=255, null=True)),
                ('Last_Updated_On', models.DateTimeField(auto_now_add=True)),
                ('Rule_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Check_Box', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='objects',
            fields=[
                ('obj_id', models.AutoField(primary_key=True, serialize=False)),
                ('obj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_project', to='connection.project')),
            ],
            options={
                'unique_together': {('project_id', 'obj_name')},
            },
        ),
        migrations.CreateModel(
            name='segments',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('segement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segement_objid', to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segement_projid', to='connection.project')),
            ],
        ),
        migrations.CreateModel(
            name='fields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('fields', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('isMandatory', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_projid', to='connection.project')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_objid', to='connection.objects')),
                ('segement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_segementid', to='connection.segments')),
            ],
        ),
    ]
